### PR TITLE
YTA-852 move logging filter from play-filters and make them use MDC cont...

### PR DESCRIPTION
**Pull request by xnejp03**
...ext to properly log the MDC values

### CODE REVIEW

**Comment by howyp** [comment]
i think we could do with some tests for the `LoggingFilter`?

**Comment by xnejp03** [comment]
I agree, but:
- currently there are none (and we only move this class)
- I don't have the time now

So either someone can do them and take ownership of YTA-852 or we merge this and create a tech debt to add hem later.

**Comment by charleskubicek** [comment]
I'll merge it for now and write tests. This whole area needs more testing and general love.

**Comment by howyp** [comment]
@charleskubicek That's kind of my point. 

I've had to retro-fit a lot of tests to be able to make improvements in http-verbs, and I think it's a pretty dangerous if we have lots of projects & services depending on code that no longer has tests attached to it.

**Pull request merged**
