### PR TITLE
YTA-704 moved FrontendAuditFilter from play-frontend here

### PR DESCRIPTION
**Pull request by xnejp03**

### CODE REVIEW

**Comment by howyp** [comment]
I'm not sure I can see the relevance to putting this filter in here?

**Comment by xnejp03** [comment]
There is already an AuditFilter for microservices. As the whole auditing code lives here, the filter kind of belongs here. Especially considering if it goes to play-filters it will need to bring dependency to http-verbs, introducing this hierarchical tree again.

**Comment by howyp** [comment]
If it was put into play-filters, what would it depend on from http-verbs? Would it just be `HeaderCarrier`?

**Comment by xnejp03** [comment]
Also AuditConnector

**Comment by howyp** [comment]
I have an idea for how we can avoid the `HeaderCarrier` dependency everywhere. And I think it'd be good to split all of the HMRC-specific audit parts out of this library, but maybe putting this filter in here for the time being is OK. 

Don't we also have a filter which converts the exceptions into results, ie. `NotFoundException` into 404s? It'd be good to have that in this library.

**Comment by xnejp03** [comment]
That is not a filter, but a Play GlobalSettings override. Still in play-frontend for now.

**Pull request merged**
