### PR TITLE
Added unapply method to HttpResponse

### PR DESCRIPTION
**Pull request by johno1985**

### CODE REVIEW

**Comment by beyond-code-github** [comment]
Thanks for this! Would you mind adding a test for completeness?

**Comment by johno1985** [comment]
Sure @beyond-code-github Shall I add a new Test class for this type? I could not find an existing one

**Comment by beyond-code-github** [comment]
Yup, go ahead

**Comment by johno1985** [comment]
@beyond-code-github unit tests have been added

**Comment by beyond-code-github** [comment]
Thanks :)

**Comment by johno1985** [comment]
No problem

**Comment by johno1985** [comment]
@beyond-code-github How soon will a new release containing these changes be available?

**Comment by beyond-code-github** [comment]
If you have access to ci-open then you can make one yourself if you like? I can talk you through the process on slack if you want

**Comment by johno1985** [comment]
Looks like I do, that would be great

**Comment by johno1985** [comment]
I'm jonathan.stearnes

**Pull request merged**
